name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint (placeholder)
        run: |
          echo "No linter configured yet."
          # Later: npx eslint .

      - name: Syntax check
        run: |
          set -e
          for f in *.js status-*.js write_status.js static-server.js; do
            [ -f "$f" ] && node -c "$f"
          done
          for f in scripts/*.sh; do
            [ -f "$f" ] && bash -n "$f"
          done

      - name: Build (placeholder)
        run: echo "Add build steps if needed."
